### DISCUSSION TITLE
Adopting clang-format for submitters

### DISCUSSION THREAD

**Discussion by wbl** [openssl/openssl#22876] [General Discussion]
Having an agreed upon code style mechanically enforced (and ideally corrected) would save reviewers and contributors much time. Could we set up clang-format or the like to do this?

**Comment by hlandau** [comment]
It is worth a try. There may be some aspects of our coding style which are too bespoke to be currently supported by clang-format.

I believe we also had some Perl-based style checking scripts in tree somewhere.

**Reply by levitte** [reply]
You're thinking of [`util/check-format.pl`](https://github.com/openssl/openssl/blob/master/util/check-format.pl)

**Comment by levitte** [comment]
There are times when such enforcement isn't great.  One example that we do have in places in our code is vertical alignment, which does increase readability.  I haven't looked up an example, but perhaps this can show you what I mean?

``` C
struct {
    int           somethingfirst;
    unsigned int  somethingelse;
};
```

vs

``` C
struct {
    int somethingfirst;
    unsigned int somethingelse;
};
```

So if we do choose to enforce mechanically, I'd advise doing so with care.

**Reply by wbl** [reply]
Clang-format is capable of doing the right thing here if configured correctly

**Reply by rsbeckerca** [reply]
Just FYI: Clang-format is not available on every platform.

**Comment by FdaSilvaYY** [comment]
A bunch of actual code is not strictly well formatted.
Using this tool, you can easily bloat any PR with unrelated style changes all along our changed file.
If style checks can be restricted to diff content, it will be better.

**Reply by wbl** [reply]
The solution there is to reformat that code in a separate big PR

**Comment by slontis** [comment]
I guess one of the problems is git blame would then look like one person changed every line.. And it would then need to be done on multiple branches to avoid merge hell.

The link here https://ortogonal.github.io/cpp/git-clang-format/ discusses using pre commit hooks, and only formatting changes.

**Reply by levitte** [reply]
Heh, so you mean that after 0f113f3ee4d629ef9a4a30911b22b224772085e5 (which was our latest big source reformat, then using GNU indent), @mattcaswell was blamed for everything?  😆

**Comment by levitte** [comment]
For those interested, we did a big source code reformat back in January 2015, using GNU indent.  For anyone interested in the git history, there's still a set of tags marking the occasion.  In chronological order: master-pre-reformat, master-pre-auto-reformat, master-post-auto-reformat, master-post-reformat

**Reply by beldmit** [reply]
And probably it's worth trying this feature

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

**Reply by wbl** [reply]
If we did reformat with indent back then, than we can just turn on indent. It's not about specific tools, its about using CI to avoid backsliding and saving committer and reviewer time.

**Comment by rsbeckerca** [comment]
Can we set this up so that the CI reports problems with the formatting and leaves it up to the contributor to fix the formatting? This takes it out of the committer's hands.

**Comment by slontis** [comment]
Thats why I mentioned the github hooks above..

**Comment by slontis** [comment]
Not sure there is quite enough control in clang-format to obey the OpenSSL coding style...
I setup the following to test
> sudo apt-get install clang-format-15


Added a .clang-format file
````
 # clang-format configuration file. Intended for clang-format >= 15.
#
# See https://clang.llvm.org/docs/ClangFormatStyleOptions.html#
#
---
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignArrayOfStructures: Right
AlignConsecutiveAssignments: None
AlignConsecutiveBitFields: None
AlignConsecutiveDeclarations: None
AlignConsecutiveMacros: None
#AlignConsecutiveShortCaseStatements:
#  Enabled: false
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments: true
#  Kind: Always
#  OverEmptyLines: 2
AllowAllArgumentsOnNextLine: false
#AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
#(18)AllowShortCompoundRequirementOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
#AllowShortLambdasOnASingleLine: None
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
#AlwaysBreakTemplateDeclarations: No
#AttributeMacros: []
BinPackArguments: true
BinPackParameters: true
BitFieldColonSpacing: Both

BreakBeforeBraces: Custom
BraceWrapping:
  AfterCaseLabel: false
  AfterClass: false
  AfterControlStatement: Never
  AfterEnum: false
  AfterFunction: true
  AfterNamespace: false
  AfterObjCDeclaration: false
  AfterStruct: false
  AfterUnion: false
  AfterExternBlock: false
  BeforeCatch: false
  BeforeElse: false
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: true
  SplitEmptyRecord: false
  SplitEmptyNamespace: false
#(17)BracedInitializerIndentWidth: 2
#(18)BreakAdjacentStringLiterals: false
#(16)BreakAfterAttributes: Never
#BreakAfterJavaFieldAnnotations: false
#(16)BreakArrays: false
BreakBeforeBinaryOperators: NonAssignment
#BreakBeforeConceptDeclarations: Never
#(16)BreakBeforeInlineASMColon: OnlyMultiline
BreakBeforeTernaryOperators: false
#BreakConstructorInitializers: AfterColon
#BreakInheritanceList: AfterColon
BreakStringLiterals: true
ColumnLimit: 80
#CommentPragmas: '^ IWYU pragma:'
#CompactNamespaces: false
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: false
DerivePointerAlignment: false
DisableFormat: false
#EmptyLineAfterAccessModifier: Leave
#EmptyLineBeforeAccessModifier: Leave
#ExperimentalAutoDetectBinPacking: false
#FixNamespaceComments: false
#ForEachMacros:[]
#IfMacros:[]
IncludeBlocks: Preserve
IncludeCategories:
  - Regex: '.*'
    Priority: 1
IncludeIsMainRegex: '*.inc'
IndentAccessModifiers: false 
IndentCaseBlocks: false
IndentCaseLabels: false
IndentExternBlock: false
IndentGotoLabels: false
IndentPPDirectives: AfterHash
IndentWidth: 4
IndentWrappedFunctionNames: false
InsertBraces: false
#(16)InsertNewlineAtEOF: true
#JavaScriptQuotes: Leave
#JavaScriptWrapImports: true
#(17)KeepEmptyLinesAtEOF: 1
KeepEmptyLinesAtTheStartOfBlocks: false
Language: Cpp
#(16)LineEnding: LF
#(17)Macros: []
MacroBlockBegin: ''
MacroBlockEnd: ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
#ObjCBinPackProtocolList: Auto
#ObjCBlockIndentWidth: 8
#ObjCSpaceAfterProperty: true
#ObjCSpaceBeforeProtocolList: true
PackConstructorInitializers: Never
PPIndentWidth: 1
# Penalties
# This decides what order things should be done if a line is too long
PenaltyBreakAssignment: 90
PenaltyBreakBeforeFirstCallParameter: 99
PenaltyBreakComment: 10
PenaltyBreakFirstLessLess: 0
PenaltyBreakOpenParenthesis: 98
PenaltyBreakString: 0
PenaltyExcessCharacter: 50
PenaltyReturnTypeOnItsOwnLine: 95
PenaltyIndentedWhitespace: 0
PointerAlignment: Right
QualifierAlignment: Leave
ReferenceAlignment: Right
ReflowComments: false
RemoveBracesLLVM: false
#(16)RemoveParentheses: Leave
#(16)RemoveSemicolon: false
SeparateDefinitionBlocks: Always
SortIncludes: Never
SortUsingDeclarations: false
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: false
SpaceAroundPointerQualifiers: Both
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
#SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
#SpaceBeforeJsonColon : true
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterForeachMacros: false
  AfterFunctionDeclarationName: false
  AfterFunctionDefinitionName: false
  AfterIfMacros: true
  BeforeNonEmptyParentheses: false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: true
SpacesBeforeTrailingComments: 1
SpacesInAngles: Never
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false

SpacesInParentheses: false
#(17)SpacesInParensOptions: Custom
#(17)SpacesInParensOptions:
#(17)  InConditionalStatements: false
#(17)  InCStyleCasts: false
#(17)  InEmptyParentheses: false
#(17)  Other: false

SpacesInSquareBrackets: false
Standard: c++03
TabWidth: 4
#(17)TypeNames: []
TypenameMacros: []
UseTab: Never
WhitespaceSensitiveMacros: []
...
````

Examples of the indenting on a small sample file...

````
    ret = EVP_PKEY_fromdata_init(ctx) > 0
          && (EVP_PKEY_fromdata(ctx, &peer->pub, EVP_PKEY_PUBLIC_KEY, params)
              > 0);
....


    if (EVP_PKEY_keygen_init(ctx) <= 0 || !EVP_PKEY_CTX_set_params(ctx, params)
        || EVP_PKEY_generate(ctx, &peer->priv) <= 0
        || !get_peer_public_key(peer, libctx)) {
        EVP_PKEY_free(peer->priv);

````
