### DISCUSSION TITLE
curl: (35) OpenSSL/3.0.13: error:0A000410:SSL routines::sslv3 alert handshake failure

### DISCUSSION THREAD

**Discussion by andrew-alton** [openssl/openssl#26393] [Q&A]
Hi Team,

I am currently working on a training project where I am using HAProxy as a proxy server with four backend servers running on Docker in a Linux environment.

When I attempt to use curl to test the setup, I encounter the following error message:

```
curl -I -L https://foo.web.debianproject.com  
curl: (35) OpenSSL/3.0.13: error:0A000410:SSL routines::sslv3 alert handshake failure  
```
HAProxy Config;

```global
  daemon
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  maxconn 4096
  tune.ssl.default-dh-param 2048

defaults
  log               global
  retries           3
  maxconn           2000
  timeout connect   5s
  timeout client    50s
  timeout server    50s
resolvers docker_resolver
   nameserver dns 127.0.0.11:53
   resolve_retries 3
   timeout retry 1s
   hold other    10s
   hold refused  10s
   hold nx       10s
   hold timeout  10s
   hold valid    10s
   hold obsolete 10s

listen stats
  bind *:9090
  stats enable
  mode http
  stats uri /
  stats refresh 10s
  stats hide-version
  stats auth admin:password

frontend https_in
     bind *:80
     bind *:443 ssl crt /usr/local/etc/haproxy/haproxy.pem alpn h2
     redirect scheme https code 301 if !{ ssl_fc }
     mode http

     acl app1 ssl_fc_sni -i foo.web.debianproject.com
     acl app2 hdr(Host) -i bar.web.debianproject.com
#    acl app3 hdr(Host) -i dar.web.mecan.ir
#
     use_backend app1_backend if app1
     use_backend app2_backend if app2
#    use_backend app3_backend if app3
     default_backend default_backend
#
# Backend for app1
     backend app1_backend
     balance roundrobin
     mode http
     server nginx-server-1 nginx-srv1:80 check resolvers docker_resolver
     server nginx-server-2 nginx-srv2:80 check resolvers docker_resolver
#
# Backend for app2
     backend app2_backend
     balance roundrobin
     mode http
    server nginx-server-3 nginx-srv3:80 check resolvers docker_resolver
#
# Backend for app3
#backend app3_backend
#    balance roundrobin
#    mode http
#    server nginx-server-3 nginx-srv3:80 check
#
## Default backend (optional)
    backend default_backend
    balance roundrobin
    mode http
    server nginx-server-4 nginx-srv4:80 check resolvers docker_resolver
#
#frontend http_front_Reverse_Proxy
#    bind *:80
#    bind *:443 ssl crt /usr/local/etc/haproxy/haproxy.pem alpn h2
#    redirect scheme https code 301 if !{ ssl_fc }
#    default_backend http_back_Reverse_Proxy
#
#backend http_back_Reverse_Proxy
#  balance roundrobin
#  mode http
#  server nginx-server-1 nginx-srv1:80 check
#  server nginx-server-2 nginx-srv2:80 check
#  server nginx-server-3 nginx-srv3:80 check

frontend microservice_http_front
  bind *:8080
  mode http
  default_backend microservice_http_back

backend microservice_http_back
  balance roundrobin
  #balance leastconn
  #balance source
  #balance static-rr
  #balance first
  mode http
  option forwardfor
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request add-header X-Forwarded-Proto https if { ssl_fc }
  server nginx-server-1 nginx-srv1:80 check
  server nginx-server-2 nginx-srv2:80 check
  server nginx-server-3 nginx-srv3:80 check
  server nginx-server-4 nginx-srv4:80 check`
```
docker compose file 

```
networks:
  app_net:
    name: app_net
    external: true

services:
  nginx-srv1:
    image: nginx:latest
    container_name: nginx-srv1
    hostname: nginx-srv1
    volumes:
      - ./nginx.srv1.html:/usr/share/nginx/html/index.html
    networks:
      - app_net

  nginx-srv2:
    image: nginx:latest
    container_name: nginx-srv2
    hostname: nginx-srv2
    volumes:
      - ./nginx.srv2.html:/usr/share/nginx/html/index.html
    networks:
      - app_net

  nginx-srv3:
    image: nginx:latest
    container_name: nginx-srv3
    hostname: nginx-srv3
    volumes:
      - ./nginx.srv3.html:/usr/share/nginx/html/index.html
    networks:
      - app_net

  nginx-srv4:
    image: nginx:latest
    container_name: nginx-srv4
    hostname: nginx-srv4
    volumes:
      - ./nginx.srv4.html:/usr/share/nginx/html/index.html
    networks:
      - app_net

  haproxy:
    image: haproxy:lts
    container_name: haproxy
    hostname: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.pem:/usr/local/etc/haproxy/haproxy.pem
    ports:
      - 9090:9090
      - 8080:8080
      - 443:443
      - 80:80
    networks:
      - app_net
 ```
Interestingly, the address works perfectly fine when accessed via a browser and reaches the correct destination.

Here are the relevant details:

- curl version: 8.5.0
- OpenSSL version: OpenSSL 3.0.13

Could you please help identify the root cause of this issue and suggest a possible resolution?

Thanks in advance!
