### DISCUSSION TITLE
How to supply context-string via pkeyutl for signing using ML-DSA

### DISCUSSION THREAD

**Discussion by Hussain1811** [openssl/openssl#27025] [Q&A] [answered]
```
root@mypc:/mnt/c/Users/oqs-provider# /opt/openssl/bin/openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.5.0-dev
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.8.1-dev
    status: active
  pkcs11
    name: PKCS#11 Provider
    version: 3.3.0
    status: active
```
