### DISCUSSION TITLE
How to verify an ML-DSA signature via pkeyutl?

### DISCUSSION THREAD

**Discussion by Hussain1811** [openssl/openssl#27034] [Q&A] [answered]
```
/opt/openssl/bin/openssl genpkey -algorithm ML-DSA-44 -provider oqsprovider -out mldsa44_priv.pem

/opt/openssl/bin/openssl genpkey -algorithm mldsa44 -outpubkey mldsa44_pub.pem -provider oqsprovider

/opt/openssl/bin/openssl pkeyutl -sign -in msg -inkey mldsa44_priv.pem -keyform PEM -provider oqsprovider -out mldsa44_sig
```

```
root@IBM-PF3XHKNA:/mnt/c/Users/oqs-provider# /opt/openssl/bin/openssl pkeyutl -verify -in msg -sigfile mldsa44_sig -inkey mldsa44_pub.pem -keyform PEM -provider oqsprovider
Could not find private key from mldsa44_pub.pem
00E084A9A67F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:crypto/store/store_result.c:157:
Segmentation fault (core dumped)
```

```
root@IBM-PF3XHKNA:/mnt/c/Users/oqs-provider# /opt/openssl/bin/openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.5.0
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.8.1-dev
    status: active
  pkcs11
    name: PKCS#11 Provider
    version: 3.3.0
    status: active
```
