### DISCUSSION TITLE
Enabling fips module

### DISCUSSION THREAD

**Discussion by Gunasekaran47** [openssl/openssl#27395] [Q&A]
When I trying to enable Fips module in openssl in windows I am getting error like this below picture. Kindly guide me steps in enabling fips module.
![tmp_48f9c259-e4fd-4c53-ad4d-b5ee76407431](https://github.com/user-attachments/assets/22e7ed3d-07a9-46ca-b368-6a403ee0654d)
[openssl.txt](https://github.com/user-attachments/files/19760485/openssl.txt)

**Comment by dovholuknf** [comment]
change base to default as in base = base_sect --> default = default sect.

add the module location to your fips_sect (or ensure the env var is set, I put it into my conf file)

Here's an example of my working openssl.conf built via vcpkg (`.\vcpkg install openssl[core,tools,fips]:x64-windows --recurse`):
```
openssl_conf = openssl_init

.include D:/git/github/microsoft/vcpkg/fipsmodule.cnf

[openssl_init]
providers = provider_sect

[provider_sect]
fips = fips_sect
default = default_sect

[fips_sect]
module = D:/git/github/microsoft/vcpkg/installed/x64-windows/bin/fips.dll
activate = 1

[default_sect]
activate = 1
```

I think using default, not base is the key maybe? 
```
.\installed\x64-windows\tools\openssl\openssl.exe list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.5.0
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.5.0
    status: active
```
