### ISSUE TITLE
Openssl 3.0 fails with loading legacy.dll and PEM_read_bio_PrivateKey returns null

### ISSUE THREAD

**Issue by alidurgun** [openssl/openssl#18700]
Hello everyone,
I was using openssl 1.1.1 and trying to upgrade our version to openssl 3.0. I have built openssl 3.0 libraries and included them into my project. After I have included these new libraries and files PEM_read_bio_PrivateKey is not working anymore. It always returns null in code.

Example Code:
unsigned char MDATA[17]; // Holds password for my key
pBio = BIO_new(BIO_s_file());
BIO_read_filename(pBio, "keyname");
PEM_read_bio_PrivateKey(pBio, NULL, 0, MDATA); // This returns null in openssl 3.0

my openssl conf I have
[provider_sect]
base = base_sect
legacy = legacy_sect

[base_sect]
activate = 1

[legacy_sect]
activate = 1

In the C++ code I am trying to load provider with:
OSSL_PROVIDER *legacy_provider;
legacy_provider = OSSL_PROVIDER_load(NULL, "legacy");

But this code fails with this error:
entry point not found for "path" legacy.dll

**Comment by xtkoba** [comment]
As for the problem with `legacy` provider, you can set the environment variable `OPENSSL_MODULES` appropriately.

**Comment by alidurgun** [comment]
I am using 
OSSL_LIB_CTX* my_libctx = OSSL_LIB_CTX_new();
OSSL_LIB_CTX_load_config(my_libctx ,"myopenssl.cnf");
When I run openssl list -providers  command I see 
```
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.0.4
    status: active
  legacy
    name: OpenSSL Legacy Provider
    version: 3.0.4
    status: active
```
  output.
  I don't understand what do you mean by set OPENSSL_MODULES variable.
