### ISSUE TITLE
openssl validates CMS with incorrect DigestAlgorithm (SignatureAlgorithm used there instead)

### ISSUE THREAD

**Issue by izderadicka** [openssl/openssl#23204]
Hi,

I have CMS which start like this:

```
CMS_ContentInfo: 
  contentType: pkcs7-signedData (1.2.840.113549.1.7.2)
  d.signedData: 
    version: 1
    digestAlgorithms:
        algorithm: sha256WithRSAEncryption (1.2.840.113549.1.1.11)
        parameter: NULL
```

where SignatureAlgorithm is misused instead of DigestAlgorithm.   OpenSSL validates message (version 3, which I have in Linux, but it seems consistent behavior across many versions):

```
$ openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
$ openssl cms -verify -noverify -inform der -in problem-data.p7s -out /dev/null -print
CMS Verification successful
```

Other libraries like Bouncy Castle refuse to validate this message.  I do have issue with BC https://github.com/bcgit/bc-java/issues/1553, where they explained to me that this is correct behaviour and validating such message is against CMS RFC. I scanned through RFCs I tend to believe they are right, as RFCs clearly distinguishes DigestAlgorithm from SignatureAlgorithm from very early RFCs - PKCS#7 and on.
Reason might be cause by some incorrect implementations - like explained in the above issue,  but I think that should be fixed sometimes.
