### ISSUE TITLE
In the openssl app list also non-configured providers present in the modules directory and providers that have configurations but are not present

### ISSUE THREAD

**Issue by petrovr** [openssl/openssl#26473]
Currently command
```sh
openssl list -providers
```
output something like this:
```
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.3.3
    status: active
  oqsprovider
    name: OpenSSL OQS Provider
    version: 0.7.1-dev
    status: active
...
```

So far so good by status output is useless. 

It seems to me command follow list of engines where and engine is listed only if is initialised. 

----

Goal of this request is command to be enhanced to list all providers defined in configuration.

For instance if provider is not activated status to indicate as inactive.
Also if provider configuration fail status to indicate failure - error or "in error" or "fail" or etc.
