### ISSUE TITLE
RSASSA PSS Error `rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding`

### ISSUE THREAD

**Issue by ricardo-reis-1970** [openssl/openssl#26797]
Hi!

I'm using:
- Linux Ubuntu 24.10
- OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
- tsget from openssl, so same version, I guess.

I have a local TSA server running on `localhost:8000/ts/`. Here are my steps:
1. I create the request in a file like this:
```bash
openssl ts -query -config x509.cnf -data 10_Visuals.pdf -no_nonce -out req.tsq
```

The config file `x509.cnf` is as follows:
```toml
[ tsa ]
default_tsa = tsa_config

[ tsa_config ]
dir               = .
serial            = $dir/serial
crypto_device     = builtin
signer_cert       = $dir/tsa.crt
certs             = $dir/ca.crt
# openssl list -digest-algorithms
signer_digest     = SHA256
signer_key        = $dir/tsa.key
default_policy    = 2.5.29.32.0
other_policies    = 2.16.756.1.89, 1.3.6.1.4.1.6189.3.4.1.1, 2.16.756.1.89.1.2.1.1, 1.1.3.4, 2.16.756.5.55.1.1, 2.16.756.1.89.1.3.1.1, 1.3.6.1.4.1.8024.0.3, 1.2.4.5
digests           = SHA256, SHA1, SHA3-512, SHA512-256
accuracy          = secs:1, millisecs:500, microsecs:100
ordering          = yes
tsa_name          = yes
ess_cert_id_chain = yes
ess_cert_id_alg   = SHA256
```

2. I use `tsget` to send a request to my server like this:
```bash
tsget -h localhost:8000/ts/ -o REQ.tsr req.tsq
```

My server has the certificate chain, which I exported to `CA.crt` and `TSA.crt`.

3. I use `openssl` to verify the result:
```bash
openssl ts -verify -queryfile req.tsq -in REQ.tsr -CAfile CA.crt -untrusted TSA.crt
```

My server has different profiles for signing these requests. If I use **RSASSA-PKCS-v1.5**, this is the result:
```bash
$ openssl ts -verify -queryfile req.tsq -in REQ.tsr -CAfile CA.crt -untrusted TSA.crt
Using configuration from /etc/ssl/openssl.cnf
Verification: OK
```

However, if I use **RSASSA-PSS** instead, I consistently get this error:
```bash
$ openssl ts -verify -queryfile req.tsq -in REQ.tsr -CAfile CA.crt -untrusted TSA.crt
Using configuration from /etc/ssl/openssl.cnf
Verification: FAILED
402743ED36770000:error:80000002:system library:process_include:No such file or directory:../crypto/conf/conf_def.c:813:calling stat(/var/lib/crypto-config/profiles/current/openssl.conf.d)
402743ED36770000:error:80000002:system library:process_include:No such file or directory:../crypto/conf/conf_def.c:813:calling stat(/etc/ssl/openssl.conf.d)
402743ED36770000:error:0200008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:../crypto/rsa/rsa_pk1.c:79:
402743ED36770000:error:02000072:rsa routines:rsa_ossl_public_decrypt:padding check failed:../crypto/rsa/rsa_ossl.c:746:
402743ED36770000:error:1C880004:Provider routines:rsa_verify:RSA lib:../providers/implementations/signature/rsa_sig.c:785:
402743ED36770000:error:10800069:PKCS7 routines:PKCS7_signatureVerify:signature failure:../crypto/pkcs7/pk7_doit.c:1125:
402743ED36770000:error:1780006D:time stamp routines:TS_RESP_verify_signature:signature failure:../crypto/ts/ts_rsp_verify.c:148:
```

Since the two certificates (the self-signed root and the TSA signer) both have signatures RSASSA-PSS, I tried verifying them:
```bash
$ openssl verify -CAfile CA.crt CA.crt 
CA.crt: OK
$ openssl verify -CAfile CA.crt TSA.crt 
TSA.crt: OK
```

So, apparently `openssl` can deal with **RSASSA-PSS**, at least in certificate signatures. But when it comes to TSP signatures, although literally the only thing that is changing here is the algorithm, PSS fails all the time.

I also generated a number of different responses to different requests with `openssl` and these all verify (except the ones with a status of `Failed`), but I could not persuade `openssl` to use any other than **PKCS-v.1.5**, so I don't really have a good comparison base.

Time is of the essence, so I'd be very glad to have at least confirmation that this is a bug on `openssl`'s side. If the files involved are needed, I'll be glad to attach them here.

Best regards,
Ricardo
