### ISSUE TITLE
.travis.yml timeout on the 4th job (2017-02-28)

### ISSUE THREAD

**Issue by levitte** [openssl/openssl#2761]
More often than not, it seems that in the current .travis.yml, the 4th job (quoted below) times out:

```
        - os: linux
          addons:
              apt:
                  packages:
                      - gcc-5
                      - g++-5
                  sources:
                      - ubuntu-toolchain-r-test
          compiler: gcc-5
          env: CONFIG_OPTS="--strict-warnings enable-tls1_3" TESTS="-test_fuzz" COMMENT="Move to the BORINGTEST build when interoperable"
```
