### ISSUE TITLE
adding Android to openssl's .travis.yml

### ISSUE THREAD

**Issue by eighthave** [openssl/openssl#8100]
I'm working on ESNI for openssl on Android, and notice that the travis-ci setup does not include Android at all.  I don't know Travis CI well enough to understand the matrix/script stuff for OpenSSL.  I have gotten the Android builds working smoothly in GitLab-CI.  So I thought someone who understands the matrix stuff would have an easy time integrating it. I have set up plain Android jobs in Travis CI, so I can help out with that part.  I just could see a way to fit that into the matrix stuff.  I'll also be working on getting the test suite running in an Android emulator, but that's not working yet.

Having this in place would catch issues like #7578 #7398 #4262

Example GitLab CI run:
https://gitlab.com/eighthave/openssl/-/jobs/147678222

YAML config file:
https://gitlab.com/eighthave/openssl/blob/master/.gitlab-ci.yml#L64
```yaml
.android-template: &android-template
  image: registry.gitlab.com/fdroid/ci-images-client
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - "*.so*"
      - "*.a"
    when:
      always
    expire_in: 1 week
  variables:
    AVD_SDK: "24"
    AVD_TAG: "default"
    AVD_PACKAGE: "system-images;android-${AVD_SDK};${AVD_TAG};armeabi-v7a"
  before_script:
    - apt-get update
    - apt-get -qy install --no-install-recommends make

android-ndk-r16b_gcc-4.9:
  <<: *android-template
  script:
    - ndk=android-ndk-r16b-linux-x86_64.zip
    - wget --quiet http://dl.google.com/android/repository/${ndk}
    - echo "bcdea4f5353773b2ffa85b5a9a2ae35544ce88ec5b507301d8cf6a76b765d901  ${ndk}" > ${ndk}.sha256
    - sha256sum -c ${ndk}.sha256
    - unzip -q $ndk
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
    - export ANDROID_NDK=$ANDROID_NDK_HOME
    - export PATH=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-14" > /dev/null
    - ./Configure android-arm -D__ANDROID_API__=14
    - make

android-ndk-r17b_gcc-4.9:
  <<: *android-template
  script:
    - ndk=android-ndk-r17b-linux-x86_64.zip
    - wget --quiet http://dl.google.com/android/repository/${ndk}
    - echo "5dfbbdc2d3ba859fed90d0e978af87c71a91a5be1f6e1c40ba697503d48ccecd  ${ndk}" > ${ndk}.sha256
    - sha256sum -c ${ndk}.sha256
    - unzip -q $ndk
    - export ANDROID_NDK_HOME=`pwd`/android-ndk-r17b
    - export ANDROID_NDK=$ANDROID_NDK_HOME
    - export PATH=$ANDROID_NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-14" > /dev/null
    - ./Configure android-arm -D__ANDROID_API__=14
    - make
```
